module.exports = {
    "sui-selected": "var(--sui-selected)",
    "sui-first": "var(--sui-first-100)",
    "sui-second": "var(--sui-second-100)",
    "sui-third": "var(--sui-third-100)",

    "sui-danger": "var(--sui-danger)",
    "sui-danger-ring": "var(--sui-danger-ring)",
    "sui-success": "var(--sui-success)",
    "sui-success-ring": "var(--sui-success-ring)",
    "sui-info": "var(--sui-info)",
    "sui-info-ring": "var(--sui-info-ring)",
    
    "sui-first-100": "var(--sui-first-100)",
    "sui-first-90": "var(--sui-first-90)",
    "sui-first-80": "var(--sui-first-80)",
    "sui-first-70": "var(--sui-first-70)",
    "sui-first-60": "var(--sui-first-60)",
    "sui-first-50": "var(--sui-first-50)",
    "sui-first-40": "var(--sui-first-40)",
    "sui-first-30": "var(--sui-first-30)",
    "sui-first-20": "var(--sui-first-20)",
    "sui-first-10": "var(--sui-first-10)",

    "sui-second-100": "var(--sui-second-100)",
    "sui-second-90": "var(--sui-second-90)",
    "sui-second-80": "var(--sui-second-80)",
    "sui-second-70": "var(--sui-second-70)",
    "sui-second-60": "var(--sui-second-60)",
    "sui-second-50": "var(--sui-second-50)",
    "sui-second-40": "var(--sui-second-40)",
    "sui-second-30": "var(--sui-second-30)",
    "sui-second-20": "var(--sui-second-20)",
    "sui-second-10": "var(--sui-second-10)",

    "sui-third-100": "var(--sui-third-100)",
    "sui-third-90": "var(--sui-third-90)",
    "sui-third-80": "var(--sui-third-80)",
    "sui-third-70": "var(--sui-third-70)",
    "sui-third-60": "var(--sui-third-60)",
    "sui-third-50": "var(--sui-third-50)",
    "sui-third-40": "var(--sui-third-40)",
    "sui-third-30": "var(--sui-third-30)",
    "sui-third-20": "var(--sui-third-20)",
    "sui-third-10": "var(--sui-third-10)",

    "sui-fourth-100": "var(--sui-fourth-100)",
    "sui-fourth-90": "var(--sui-fourth-90)",
    "sui-fourth-80": "var(--sui-fourth-80)",
    "sui-fourth-70": "var(--sui-fourth-70)",
    "sui-fourth-60": "var(--sui-fourth-60)",
    "sui-fourth-50": "var(--sui-fourth-50)",
    "sui-fourth-40": "var(--sui-fourth-40)",
    "sui-fourth-30": "var(--sui-fourth-30)",
    "sui-fourth-20": "var(--sui-fourth-20)",
    "sui-fourth-10": "var(--sui-fourth-10)",

    "sui-dark": "var(--sui-dark-100)",
    "sui-dark-100": "var(--sui-dark-100)",
    "sui-dark-90": "var(--sui-dark-90)",
    "sui-dark-80": "var(--sui-dark-80)",
    "sui-dark-70": "var(--sui-dark-70)",
    "sui-dark-60": "var(--sui-dark-60)",
    "sui-dark-50": "var(--sui-dark-50)",
    "sui-dark-40": "var(--sui-dark-40)",
    "sui-dark-30": "var(--sui-dark-30)",
    "sui-dark-20": "var(--sui-dark-20)",
    "sui-dark-10": "var(--sui-dark-10)",
}